repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-treeval_logo_light.png
    - docs/images/nf-core-treeval_logo_light.png
    - docs/images/nf-core-treeval_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
