repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-treeval_logo_light.png
    - conf/test_full.config
    - docs/images/nf-core-treeval_logo_light.png
    - docs/images/nf-core-treeval_logo_dark.png
    - conf/igenomes.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  repository_type: pipeline
  template:
    author: DLBPointon, yumisims, weagles
    description: Generating data for the manual curation of genomic assemblies
    name: treeval
    prefix: sanger-tol
    skip:
      - igenomes
