repository_type: pipeline
<<<<<<< HEAD
lint:
  files_unchanged:
    - LICENSE
    - .gitattributes
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting_comment.yml
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
=======
>>>>>>> origin/TEMPLATE
